isce-framework/dolphin

- docs/requirements.txt
- mkdocs.yml
- src/dolphin/ps.py
the readthedocs one is badly spaced and hard to read
> switch to material docs theme

- src/dolphin/_background.py
- src/dolphin/io.py
- src/dolphin/sequential.py
this should fix #40 when saving the strided MLE outputs
> add `strides` option to `write_arr`

- src/dolphin/workflows/config.py
- tests/test_workflows_config.py
This should close the requests made in #37 .
Also ensures that all fields have descriptions and types.
> add commented descriptions to `to_yaml` method of Workflow

- pyproject.toml
- src/dolphin/phase_link/_mle_cpu.py
- src/dolphin/phase_link/_mle_gpu.py
- src/dolphin/phase_link/mle.py
- src/dolphin/phase_link/simulate.py
- src/dolphin/sequential.py
- src/dolphin/workflows/config.py
- src/dolphin/workflows/wrapped_phase.py
- tests/conftest.py
This should make nearly no difference in the estimated phase of the output, but it will make barely-singular matrices invertible.
Regularization of 0.01 will subtract 0.01 from the correlation magnitude in the Gamma matrix that gets inverted.
This fixes #35 and fixes #43
> set default regularization beta=0.01

- src/dolphin/io.py
- src/dolphin/stitching.py
- src/dolphin/unwrap.py
There were cases where the name of the warped file in the directory would overwrite others, so this makes the name unique.
> fix the repeated name of the warping

- .github/workflows/tests.yml
- CHANGELOG.md
- conda-env.yml
- pyproject.toml
- src/dolphin/_background.py
- src/dolphin/_types.py
- src/dolphin/cli.py
- src/dolphin/io.py
- src/dolphin/stitching.py
- src/dolphin/unwrap.py
- src/dolphin/workflows/s1_disp.py
- src/dolphin/workflows/sequential.py
- src/dolphin/workflows/stitch_and_unwrap.py
- tests/conftest.py
- tests/test_cli.py
- tests/test_unwrap.py
closes #29
Also fixes a small bug with averaging tcorr in the stack workflow, since the nodata was actually 0, not nan
> use isce3 to unwrap instead of hand-rolled snaphu

- CHANGELOG.md
- scripts/release/generate_product_docx_table.py
- scripts/release/validate_product.py
- src/dolphin/workflows/_product.py
- src/dolphin/workflows/_yaml_model.py
- src/dolphin/workflows/s1_disp.py
- src/dolphin/workflows/stitch_and_unwrap.py
- src/dolphin/workflows/wrapped_phase.py
Last minor changes before releasing v0.1
Biggest addition is the compressed SLC HDF5 generation, which tries to match the structure of COMPASS outputs and store them with names like `compressed_slc_<burst>_<start date>_<end date>.h5`
> Last IF changes

- scripts/release/generate_product_docx_table.py
- scripts/release/list_packages.py
- src/dolphin/_show_versions.py
- src/dolphin/interferogram.py
- src/dolphin/io.py
- src/dolphin/masking.py
- src/dolphin/phase_link/_mle_cpu.py
- src/dolphin/phase_link/_mle_gpu.py
- src/dolphin/phase_link/covariance.py
- src/dolphin/phase_link/mle.py
- src/dolphin/stack.py
- src/dolphin/stitching.py
- src/dolphin/unwrap.py
- src/dolphin/utils.py
- src/dolphin/workflows/_cli_config.py
- src/dolphin/workflows/_pge_runconfig.py
- src/dolphin/workflows/_product.py
- src/dolphin/workflows/_utils.py
- src/dolphin/workflows/config.py
- src/dolphin/workflows/s1_disp.py
- src/dolphin/workflows/sequential.py
- src/dolphin/workflows/single.py
- src/dolphin/workflows/stitch_and_unwrap.py
- src/dolphin/workflows/wrapped_phase.py
- tests/test_workflows_s1_disp.py
makes it 3.9 compatible by adding __future__.annotations
> Switch typing to `list`/`dict`/`tuple`

- CHANGELOG.md
- conda-env.yml
- src/dolphin/interferogram.py
- src/dolphin/io.py
- src/dolphin/stack.py
- src/dolphin/stitching.py
- src/dolphin/utils.py
- src/dolphin/workflows/_utils.py
- src/dolphin/workflows/config.py
- src/dolphin/workflows/wrapped_phase.py
- tests/conftest.py
- tests/make_netcdf.py
- tests/test_interferogram.py
- tests/test_stack.py
- tests/test_workflows_config.py
- tests/test_workflows_pge_runconfig.py
Note: the old versions of data may be adjusted to work with the new code by adding symlinks as follows:
```python
def symlink_new(filename):
with h5py.File(filename, 'a') as hf:
hf['data'] = hf['science/SENTINEL1/CSLC/grids']
hf['identification'] = hf['science/SENTINEL1/identification']
hf['metadata'] = hf['science/SENTINEL1/CSLC/metadata/']
```
> Update the `OPERA_` datasets for the new COMPASS spec.

- CHANGELOG.md
- README.md
- conda-env-gpu-extras.yml
- conda-env.yml
- docker/Dockerfile
- docker/build-docker-image.sh
- docs/getting-started.md
- pyproject.toml
- src/dolphin/_show_versions.py
Alternative to the changes in #125 .
> Add back `isce3` to avoid optional installs

- conda-env-unwrapping.yml
- docker/Dockerfile
Will remove this once conda forge is up
> add tophu manual pip install to dockerfile

- src/dolphin/opera_utils.py
- src/dolphin/workflows/_cli_config.py
- src/dolphin/workflows/_enums.py
- src/dolphin/workflows/config.py
- src/dolphin/workflows/wrapped_phase.py
- tests/test_workflows_s1_disp.py
- No need to for the specific name
- Always use the Sequential, even if there's one ministack
> Remove `WorkflowName` from `Workflow`

- CHANGELOG.md
- src/dolphin/opera_utils.py
- src/dolphin/workflows/_cli_config.py
- src/dolphin/workflows/config.py
- Does not implement the corrections yet.
- Adds a `--keep-paths-relative` option so that you can create a config file which still works when run in docker with different absolute paths
> Add `CorrectionsGroup` to config to track files for future corrections

- CHANGELOG.md
- src/dolphin/interferogram.py
- src/dolphin/workflows/wrapped_phase.py
- tests/test_interferogram.py
This lets us use `max_bandwidth` from the results of phase linking to form a network of interferograms to unwrap.
> Manually specify dates for `Network`

- src/dolphin/interferogram.py
- src/dolphin/io.py
- src/dolphin/workflows/wrapped_phase.py
- tests/test_interferogram.py
Also adds `overview` support to `load_gdal` for quicklooks.
> Add ability to make annual ifgs in `Network`

- src/dolphin/workflows/_cli_config.py
> Expose `--no-unwrap` in `dolphin config` to skip unwrapping

- src/dolphin/workflows/_cli_config.py
- src/dolphin/workflows/config/_common.py
- src/dolphin/workflows/displacement.py
- tests/test_workflows_config.py
- tests/test_workflows_displacement.py
- tests/test_workflows_sequential.py
- tests/test_workflows_single.py
With the CPU version being fast, there would need to be more fine-tuning/JAX option tinkering to make the GPU version much faster than CPU (assuming we're running multiple bursts in parallel)
> Disable gpu by default

- .github/workflows/test-build-push.yml
- docker/Dockerfile
- src/dolphin/unwrap/_snaphu_py.py
- src/dolphin/workflows/wrapped_phase.py
https://github.com/isce-framework/snaphu-py/commit/a77cbe1ff115d96164985523987b1db3278970ed
> Change snaphu-py tile defaults to avoid max secondary arcs error

- .github/workflows/test-build-push.yml
- src/dolphin/atmosphere/ionosphere.py
- src/dolphin/atmosphere/troposphere.py
- src/dolphin/workflows/displacement.py
some minor bugs found and corrected after running delivery data
> minor corrections for disp-s1

- src/dolphin/workflows/_cli_config.py
- src/dolphin/workflows/displacement.py
Add option to toggle inversion in the config function. By default set to true, like for unwrapping.
This allows for more flexibility when running especially large-scale processing.
>  Add option to toggle off inversion

- .github/dependabot.yml
https://github.com/isce-framework/snaphu-py/pull/52
> Create dependabot.yml for grouping updates

- CHANGELOG.md
Updated changelog for version 0.17.0
> update the change log

- src/dolphin/_cli_timeseries.py
- src/dolphin/cli.py
- src/dolphin/timeseries.py
- src/dolphin/workflows/config/_enums.py
- src/dolphin/workflows/displacement.py
- tests/test_cli.py
Added the timeseries step to command line to be able to run separate from workflow
> Cli timeseries

- src/dolphin/stitching.py
This accounts for the nonlinear edge warping. The current version using only two corner points will not be a completely correct warped bounding box.
> Change `reproject_bounds` to use rasterio version

- src/dolphin/filtering.py
- tests/test_filtering.py
filtering.py
test_filtering.py
> Add filtering module for unwrapped interferogram

- src/dolphin/goldstein.py
- src/dolphin/phase_link/_core.py
- src/dolphin/phase_link/_ps_filling.py
- src/dolphin/timeseries.py
- tests/test_phase_link_core.py
Replaced several other `asserts` in favor of `if ... raise ValueError(..)`
> Fix bad assert in phase linking code

- src/dolphin/phase_link/_core.py
- src/dolphin/phase_link/_ps_filling.py
- tests/test_phase_link_core.py
- tests/test_phase_link_ps_filling.py
Fixes other optional `ndarray`/`ArrayLike` mistypings
> Add more PS filling tests

- CHANGELOG.md
- src/dolphin/unwrap/_unwrap.py
- Raster metadata was missing when running interpolation
- By default delete scratchdir (#249)
> Fix unwrap metadata, delete unwrap scratch by default

- src/dolphin/__init__.py
- src/dolphin/atmosphere/_utils.py
- src/dolphin/atmosphere/weather_model.py
- src/dolphin/interpolation.py
removes `pandas` from the default import path by keeping within `atmosphere`
> Fix v022 imports

- src/dolphin/unwrap/_unwrap_3d.py
https://github.com/isce-framework/spurt/pull/29
> Update `spurt` imports for exported interface

- src/dolphin/unwrap/_unwrap.py
- tests/test_unwrap.py
> Set the `final_arr` nodata to be same as original ifg mask

- src/dolphin/atmosphere/_netcdf.py
the datetime format should be "datetime64[s]" as default
> change datetime format

- src/dolphin/_cli_filter.py
- src/dolphin/cli.py
- src/dolphin/filtering.py
- tests/test_cli.py
- tests/test_filtering.py
Usage: 
```
dolphin filter --unw-filenames unwrapped/*unw.tif -o filtered
```
> Add `dolphin filter` cli to run a long wavelgnth filter on a set of rasters

- src/dolphin/workflows/config/_unwrap_options.py
Updates for https://github.com/isce-framework/spurt/pull/33 and https://github.com/isce-framework/spurt/pull/35
> Add `num_parallel_tiles` and `num_parallel_ifgs` to `SpurtOptions`

- src/dolphin/utils.py
This should still probably be moved elsewhere from the too-specific assumptions about OPERA data format,but that can be a separate PR.
> Include layover shadow mask when stitching in `prepare_geometry`

- .github/workflows/test-build-push.yml
- src/dolphin/io/_utils.py
- tests/test_io_utils.py
> Refactor `repack_raster` to work in block for lower memory

- docs/requirements.txt
- src/dolphin/_cli_timeseries.py
- src/dolphin/timeseries.py
https://github.com/danielfrg/mkdocs-jupyter/issues/212 seems to affect the latest so math doesnt render
> Pin `mkdocs-jupyter` to 0.25.0, small `timeseries` fix for cli

- conda-env.yml
- pyproject.toml
- src/dolphin/_cli_unwrap.py
- src/dolphin/_log.py
- src/dolphin/_overviews.py
- src/dolphin/filtering.py
- src/dolphin/goldstein.py
- src/dolphin/interpolation.py
- src/dolphin/io/_process.py
- src/dolphin/phase_link/_compress.py
- src/dolphin/phase_link/metrics.py
- src/dolphin/phase_link/simulate.py
- src/dolphin/similarity.py
- src/dolphin/stack.py
- src/dolphin/timeseries.py
- src/dolphin/unwrap/_post_process.py
- src/dolphin/unwrap/_unwrap_3d.py
- src/dolphin/workflows/_cli_run.py
- src/dolphin/workflows/config/_yaml_model.py
- import needed to not error when using 3.9
- `Optional` or `Union` needed in the [modules which use Pydantic](https://github.com/pydantic/pydantic/pull/8209)
> Add missing annotations to make Python 3.9 compatible

- src/dolphin/phase_link/simulate.py
Refactors the pixelwise simulation to have seasonal option. Does not change normal existing tests.
> `simulate.py`: Add `use_seasonal_coherence`, remove numba

- src/dolphin/workflows/wrapped_phase.py
Adding subdataset as input arguments because it is different for S1 and NISAR
> Nisar datasets

- mkdocs.yml
https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
> Add Github link to docs

- MANIFEST.in
> Remove old `glrt_cutoffs.csv` from `MANIFEST.in`

- src/dolphin/io/_readers.py
> Revert API change for `_readers` from #579

- src/dolphin/workflows/unwrapping.py
Found by @giorgoskouroupis in https://github.com/isce-framework/dolphin/discussions/590#discussioncomment-13365346
> `unwrapping.py`: fix comparison to avoid mask warping
