isce-framework/dolphin

README.md
src/dolphin/sequential.py
tests/test_ps.py

https://github.com/opera-adt/dolphin/actions/runs/4019914684/jobs/6907299026
older gdal_calc seems to be unable to accept the Path as outfile
the numpy warning used to be true_divide. so make the regex less specific

fix sequential test failing on min-deps.

---

.pre-commit-config.yaml
pyproject.toml
src/dolphin/_background.py
src/dolphin/io.py
src/dolphin/ps.py
src/dolphin/sequential.py
src/dolphin/stack.py
src/dolphin/stitching.py
src/dolphin/workflows/_config_cli.py
src/dolphin/workflows/config.py
tests/conftest.py
tests/test_io.py
tests/test_stack.py
tests/test_workflows_config.py

Moving the chunk loading and writing for the PS/wrapped phase/stitching steps into a background thread.
See https://github.com/opera-adt/dolphin/issues/6#issuecomment-1413992976 for performance improvement analysis, summary is that processing 2 bursts of a stack went from ~15 minutes to ~6 minutes.
Other notes:
- Although the `_background.py` module is currently copied over from isce3, if isce3 becomes a mandatory dependency of dolphin, we will just remove this module and keep the derived classes.
- some of the other changes were to remove (currently) unused functions
- Fixed numpy-related dtypes to use their built in `numpy.typing` module

Background io

---

pyproject.toml
src/dolphin/phase_link/covariance.py
src/dolphin/phase_link/mle.py
tests/test_phase_link_mle.py

The key step this time was `arr = arr.copy() + 1e-5 * np.random.rand(*arr.shape)`, since the `_find_maxes` function was getting confused by ties, which led to a different number of pixels being requested to be filled.

Ps fill fix

---

src/dolphin/io.py
src/dolphin/stitching.py

this was leading to an occasional error
```python traceback
File "/u/aurora-r0/staniewi/miniconda3/envs/mapping/bin/dolphin", line 8, in <module>
sys.exit(main())
File "/u/aurora-r0/staniewi/repos/dolphin/src/dolphin/cli.py", line 22, in main
run_func(**arg_dict)
File "/u/aurora-r0/staniewi/repos/dolphin/src/dolphin/_log.py", line 94, in wrapper
result = f(*args, **kwargs)
File "/u/aurora-r0/staniewi/repos/dolphin/src/dolphin/workflows/_run_cli.py", line 26, in run
s1_disp_stack.run(cfg, debug=debug)
File "/u/aurora-r0/staniewi/repos/dolphin/src/dolphin/_log.py", line 94, in wrapper
result = f(*args, **kwargs)
File "/u/aurora-r0/staniewi/repos/dolphin/src/dolphin/workflows/s1_disp_stack.py", line 67, in run
unwrapped_paths = stitch_and_unwrap.run(ifg_list, cfg, debug=debug)
File …
```

fix rounding/loading shapes for stitching

---

src/dolphin/_log.py
src/dolphin/interferogram.py
src/dolphin/stack.py
src/dolphin/stitching.py
src/dolphin/workflows/__init__.py
src/dolphin/workflows/_grouping.py
src/dolphin/workflows/s1_disp.py
tests/test_workflows_s1_disp.py

- Fixes a stitching error which would only sometimes come up. We were writing in a background thread, but that would sometimes lead to results like this:
This is the fix:
(where the upper right line artifact is unrelated to the stitching, but is a DEM difference)
- Makes some of the input type hints more general
- Removes the check on number of bands in the VRTStack XML parsing so that we can use it on VRTInterferogram (which has one band, but two files)

Workflow tweaks

---

src/dolphin/_background.py
src/dolphin/io.py
src/dolphin/phase_link/_mle_cpu.py
src/dolphin/phase_link/_mle_gpu.py
src/dolphin/phase_link/mle.py
src/dolphin/stack.py
src/dolphin/utils.py
tests/test_io.py

#57 has more detail on the main problem this is addressing: When using a downsampled output (strides > 1), use the average PS within each stride window
This also fixes
- a problem where the script would hang after an exception because of a queue backup for the `EagerLoader`
- a speedup for the CPU version, where we're using scipy's `eigh`, which can compute only a single eigenvector.

Fix strided output PS filling

---

src/dolphin/workflows/_product.py

Small change to the output product structure.
We were populating a global attribute called "description" whose value was "Phase corrections applied to the unwrapped_phase". I think this was actually intended to describe the "/corrections" group instead.

Fix corrections group description

---

scripts/release/list_packages.py

Add a script to populate a CSV file with a list of conda & yum packages installed within the deliverable image. This can be used to document the image contents for OPERA ADT releases.
Example usage:
```console
$ RELEASE="L3_DISP_S1"
$ ./list_packages.py opera-adt/dolphin:latest -e "/usr/local/bin/_entrypoint.sh" > "${RELEASE}_Package_Version_Table.csv"
```
Some sample output looks like this:
```console
$ (head; echo "..."; tail) < "${RELEASE}_Package_Version_Table.csv"
Name,Version,Package Manager,Channel
_libgcc_mutex,0.1,conda,conda-forge
_openmp_mutex,4.5,conda,conda-forge
backoff,2.2.1,conda,conda-forge
blosc,1.21.3,conda,conda-forge
boost-cpp,1.78.0,conda,conda-forge
brotlipy,0.7.0,conda,conda-forge
bzip2,1.0.8,conda,conda-forge
c-ares,1.18.1,conda,conda-forge …
```

Add tool to list installed packages

---

scripts/release/validate_product.py

If the phase was unwrapped using the ICU algorithm, unwrapping results may not be reproducible on different platforms (even with a fixed seed). In order to avoid spurious validation failures, this PR weakens the validation checks that are performed on the connected component labels and unwrapped phase datasets.
The connected component labels are now validated based on the overlap between the nonzero-labeled regions in the test dataset and the reference dataset. The code creates a binary mask of nonzero labels in each dataset and computes the intersection of the two masks. Validation fails if the intersection area was below some threshold relative to the reference mask area.
The unwrapped phase will now fail validation if the phase values (A) contain too many NaN values, or (B) are not …

Weaken validation of connected component labels and unwrapped phase

---

src/dolphin/io.py
src/dolphin/shp/_glrt.py
src/dolphin/workflows/s1_disp.py
tests/test_io.py

Error found from `sweets` testing, since it needed both kinds before, and you also couldn't pass a `None` or `slice(None)`.
Two other commented code sections removed.

Fix `load_gdal` to accept one type of row/col slice

---

.pre-commit-config.yaml
src/dolphin/workflows/config.py

the type:ignores came up at astrange time, possibly because it was using version 2

try capping precommit pydantic

---

src/dolphin/workflows/stitch_and_unwrap.py

Quick fix so that radar-coordinate masks can be used (which would fail during the `gdalwarp` step)

skip warping a mask if already the same size

---

src/dolphin/io.py
src/dolphin/workflows/single.py
tests/conftest.py
tests/test_io.py
tests/test_workflows_sequential.py

- double the half window size for overlap
- change the `single.py` outputs to use a trimmed slice
- fix tests accordingly
This should close #73

Implement overlap trimming for blockwise IO

---

CHANGELOG.md
src/dolphin/interferogram.py
src/dolphin/phase_link/mle.py
src/dolphin/ps.py
src/dolphin/stitching.py
src/dolphin/workflows/config.py
src/dolphin/workflows/single.py
src/dolphin/workflows/stitch_and_unwrap.py
src/dolphin/workflows/wrapped_phase.py

- Adds a multilooked PS mask file to the saved Workflow outputs
- Adds `bounds` to the workflow config so we can specify exact boundaries, ensuring that missing bursts for a frame don't change the boundary results
- lets the interferogram `Network` accept a sequence of `subdataset`s
This PR closes #102

Save multilooked PS file, workflow bounds

---

.github/workflows/test-build-push.yml
CHANGELOG.md
README.md
conda-env.yml
docs/getting-started.md
pyproject.toml
src/dolphin/_background.py
src/dolphin/ps.py
src/dolphin/utils.py
src/dolphin/workflows/_utils.py
src/dolphin/workflows/s1_disp.py
src/dolphin/workflows/stitch_and_unwrap.py
src/dolphin/workflows/wrapped_phase.py
tests/requirements.txt
tests/test_shp.py

Additionally, fix a few other random problems/tidying bits.

Fix the multilooked PS mask output

---

conda-env.yml
src/dolphin/workflows/config.py

- Testing if adding the `tbb` library fixes some of the CI issues.
- also fixing the last two uses of lowercase typing `list/dict/tuple` in `config.py` which pydantic doesn't like in python 3.8.

add tbb to prevent numba crashes

---

.github/workflows/test-build-push.yml
.pre-commit-config.yaml
src/dolphin/_cli_unwrap.py
src/dolphin/interferogram.py
src/dolphin/unwrap.py
src/dolphin/workflows/_utils.py
src/dolphin/workflows/config.py
src/dolphin/workflows/stitch_and_unwrap.py
tests/test_unwrap.py
tests/test_workflows_config.py

- Finally addresses #10 
- Also removes coarse_unwrap, which is subsumed by this.
- TBD: 
- how to handle tophu as an optional/mandatory dependency. It uses dask + rasterio. Neither of these are required right now, even though I've considered switching certain things to it (and code could be cut if I fully committed to `rasterio`)
- number of `tophu` options to expose in the `Workflow`, especially if I have it as an optional dep.

Add ability to unwrap using `tophu`

---

src/dolphin/io.py
src/dolphin/stack.py
src/dolphin/utils.py
src/dolphin/workflows/single.py

- Uses the gdal metadata "DOLPHIN" domain to hold the input filename
- PR also includes some general variable renaming for clarify

Add metadata to compressed SLCs to track input files

---

.github/workflows/test-build-push.yml
CHANGELOG.md
src/dolphin/unwrap.py
src/dolphin/workflows/config.py
src/dolphin/workflows/s1_disp.py
src/dolphin/workflows/stitch_and_unwrap.py
tests/test_workflows_config.py

We were creating the PS mask, but not passing the filename through to make saving it easy.

Return ps mask, use `scratchdir` for tophu unwrapping

---

.github/workflows/benchmark.yml
asv.conf.json
benchmarks/README_CI.md
benchmarks/benchmarks.py
scripts/test_run_bench.sh
tests/requirements.txt

(Dumping some of my initial notes about why I ended up picking this)
Airspeed Velocity ([`asv`](https://asv.readthedocs.io/en/v0.6.1/)) seems to be the best existing way to run a few benchmarks and get progress over time. It's used by `numpy`, `pandas`, `scikit-image`, `xarray`, and a few others.
1. I installed `asv` (which is added to the `test` requirements), ran `asf quickstart` to make a template `asv.conf.json`, then filled it out
2. To run locally, you can run `asv machine` or `asv machine --yes` to have it save info about the computer you are on
3. Runing benchmarks with `asv run` will install the environment(s) that are specified, and these can be reused for future runs.
4. You compile the results with `asv publish`, and view locally with `asv preview`
The benchmarks almost look …

`asv` benchmark setup

---

src/dolphin/_decorators.py
tests/test_decorators.py

Used for long running parts where, if a process is interrupted, currently there would be a half-empty file with the expected output name. This replaces the final output name with a tempfile, then swaps it only after the process is complete.
closes #110

Add `@atomic_output` decorator for outputs that get written to in blocks

---

tests/test_workflows_displacement.py

Making a more thorough test for when we split up ministacks into completely separate workflow runs. Just verifying the fixes from #164

Add unit test for separate workflows with CCSLCs

---

src/dolphin/unwrap.py
src/dolphin/workflows/displacement.py
src/dolphin/workflows/sequential.py
src/dolphin/workflows/single.py
src/dolphin/workflows/stitch_and_unwrap.py
src/dolphin/workflows/wrapped_phase.py
tests/test_workflows_single.py

- `tcorr` is a bad name
- add the date range to the output filename from `sequential` so we can merge directories later without clobbering
- Add `unwrap_callback` to `unwrap.multiscale_uwnrap` so we can pass any function to `tophu`

Switch naming from `tcorr`, add `unwrap_callback` argument option

---

.pre-commit-config.yaml
CHANGELOG.md
pyproject.toml

Take more `pyproject.toml` config from Geoff

Drop pydocstyle in pre-commit

---

src/dolphin/_types.py
src/dolphin/io.py
src/dolphin/stitching.py
src/dolphin/workflows/config/_common.py
src/dolphin/workflows/stitching_bursts.py

This gives more clarity to what the 4 `float` are in the tuple, and lets us call them by name (i.e. `bbox.left`)

Switch the `Bbox` type to a `namedtuple`

---

.github/workflows/test-build-push.yml
CHANGELOG.md
conda-env.yml
mkdocs.yml
pyproject.toml
requirements.txt
src/dolphin/_background.py
src/dolphin/_readers.py
src/dolphin/io.py
src/dolphin/ps.py
src/dolphin/utils.py
src/dolphin/workflows/ps.py
src/dolphin/workflows/wrapped_phase.py
tests/conftest.py
tests/test_io.py
tests/test_ps.py
tests/test_readers.py

Some timing results on a test where I had
- 80 total rasters, shape of the input stack was `(80, 2160, 3600)`
- Saved in formats
- `.bin`: flat binary/ENVI
- `.h5`: HDF5 with gzip
- `.lzf.h5`: HDF5 with lzf compression
- `.tif`: geotiff with dolphin default compression options
- reading over all bands of (512, 512) blocks at a time, and summing up the values (just to do something with the data)
HDF5StackReader:
```
(mapping-311) opera-test-data$ python test_read.py --reader-class HDF5StackReader data/*[0-9].h5
Read times              
┏━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━┓
┃ keep_open ┃ num_threads ┃ time (s) ┃
┡━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━┩
│ False     │ 1           │ 4.517    │
│ False     │ 3           │ 4.901    │
│ False     │ 10          │ 7.138    │
│ True      │ 1 …
```

Add `RasterReader` and `RasterStackReader` implementations

---

src/dolphin/stitching.py
tests/conftest.py
tests/test_stitching.py

Two changes need to fix this:
1. we were passing `strides` to `get_combined_bounds_nodata`, even thought we already used it in `get_downsampled_vrts`. this meant it was double counting the strided output resolution, leading to that weird rounding error in @taliboliver 's example
2. Now we do a `gdal_translate` after merging, since `gdal_merge` has no resampling algorithm to guarantee the output bounds.

Fix `merge_images` for strided images

---

src/dolphin/interferogram.py
src/dolphin/stitching.py
src/dolphin/workflows/stitching_bursts.py
tests/test_stitching.py
tests/test_workflows_displacement.py

I had initially set it to use ENVI format (with ".int" and ".cor" as the extensions) so that you could run the standalone snaphu right on the outputs, as it needs files in the flat-binary format. Now that https://github.com/isce-framework/snaphu-py exists, we might as well use a format with some compression.
As a bonus, this will also make it easier to browse outputs after running `gdaladdo` on the interferograms/correlations

Use `.int.tif` for default stitched interferograms

---

src/dolphin/workflows/config/_common.py
src/dolphin/workflows/config/_displacement.py
src/dolphin/workflows/config/_ps.py
src/dolphin/workflows/config/_unwrapping.py
src/dolphin/workflows/single.py

Earlier version of pydantic didn't have this.
Currently overriding `__init__` loses the type info:
Now we have them when creating new objects:

use `model_post_init` instead of overriding `__init__`

---

src/dolphin/interferogram.py
src/dolphin/stitching.py
tests/test_stitching.py

Should close #204
Testing on 2 bursts, where
```
$ grep -c t042_088905_iw1 dolphin_config.yaml
12
$ grep -c t042_088906_iw1 dolphin_config.yaml
3
$
```
Before:
```
$ shape interferograms/*.int.tif
interferograms/20221119_20221201.int.tif
1 2222,3524
interferograms/20221119_20221213.int.tif
1 2222,3524
interferograms/20221119_20230106.int.tif
1 1613,3253
interferograms/20221119_20230118.int.tif
1 1613,3253
....
```
After PR:
<details>
```
$ shape interferograms/*.int.tif
interferograms/20221119_20221201.int.tif
1 2222,3524
interferograms/20221119_20221213.int.tif
1 2222,3524
interferograms/20221119_20230106.int.tif
1 2222,3524
interferograms/20221119_20230118.int.tif
1 2222,3524
interferograms/20221119_20230130.int.tif
1 2222,3524
interferograms/20221119_20230211.int.tif
1 2222,3524 …
```

Apply `out_bounds` during stitching even if only 1 image exists

---

src/dolphin/workflows/displacement.py
tests/test_workflows_displacement.py

Should lead to less code repetition in `disp-s1`, fewer changes that we need to account for in two places

Return the output paths from `DisplacementWorkflow`

---

src/dolphin/_overviews.py
src/dolphin/phase_link/_core.py
src/dolphin/workflows/config/_common.py

Also fixes overviews log formatting

Allow `None` or `int` for `ntiles`/`downsample_factor`

---

CHANGELOG.md
src/dolphin/unwrap/_constants.py
src/dolphin/unwrap/_isce3.py
src/dolphin/unwrap/_snaphu_py.py
src/dolphin/unwrap/_tophu.py
src/dolphin/unwrap/_unwrap.py
src/dolphin/unwrap/_utils.py
tests/test_unwrap.py
tests/test_unwrap_utils.py

- Combine the nodata region with the `mask_file` to pass through to unwrappers
- Update regions which are nodata in interferograms to be nodata in unwrapped phase
- Use `uint16` data type for connected component labels
Before
after

Better nodata/mask handling in `dolphin.unwrap`

---

CHANGELOG.md
src/dolphin/io/_core.py
src/dolphin/unwrap/_snaphu_py.py
src/dolphin/unwrap/_tophu.py
src/dolphin/workflows/wrapped_phase.py

Currently it's make big, uncompressed tif files. Pass through the rasterio-version of the default GTiff options

Use compression/tiling by default in snaphu outputs

---

CHANGELOG.md
src/dolphin/phase_link/_core.py
tests/test_phase_link_core.py

This should fix #84
Left is current problem from shifting SLC bursts leading to bad edges, right is correctly keeping only the intersection of the good data footprints.

Set intersection of nodata in SLC stack to `nan` in `run_phase_linking`

---

.github/workflows/test-build-push.yml
docker/Dockerfile
src/dolphin/unwrap/_isce3.py
src/dolphin/unwrap/_unwrap.py
src/dolphin/workflows/unwrapping.py

The order was switched for the input/output rasters when not using Tophu.
Now jump straight to using tophu.

Fix phass unwrap

---

conda-env.yml

Consistency between jax and jaxlib can be enforced by installing the most recent versions via pip, which is currently not possible through conda where the two packages are out of sync.
This is necessary as dolphin would crash early on in processing if the two packages are not in sync.

Enforce consistency between jax and jaxlib

---

CHANGELOG.md
src/dolphin/io/_readers.py
src/dolphin/timeseries.py
src/dolphin/utils.py
src/dolphin/workflows/config/_common.py
src/dolphin/workflows/displacement.py
tests/conftest.py
tests/test_io_readers.py
tests/test_workflows_config.py
tests/test_workflows_displacement.py

The corrections portion of `tests/test_workflows_displacement.py::test_displacement_run_single_official_opera_naming` was never running due to the setting `run_unwrap=False`.
I tried to get the fake opera data working, but i can't get the geo metadata right (even after all this time spent in `product.py`). I'm not even sure that it would work with the different, smaller fake SLCs for the test. So i've disabled.
In the course of trying to make it work, I found 3 other bugs
- A length 1 `StackReader` will return a 2d array, since gdal squeezes the extra dimension out. This caused errors for the time series portion
- The pydantic config validator prevented `max_bandwidth=1` since it had `gt=3`. Changed to `ge=1`.
- A failure to find any valid connected component area would give a bad error. …

Disable corrections part of pytest, add one for timeseries

---

src/dolphin/io/__init__.py
src/dolphin/io/_process.py
src/dolphin/io/_writers.py
src/dolphin/similarity.py
src/dolphin/timeseries.py
src/dolphin/workflows/single.py
tests/test_similarity.py
tests/test_timeseries.py

- main function: `dolphin.similarity.median_similarity`
- moves `process_blocks` into an `dolphin.io` export to use from more places besides `timeseries`

Add `similarity` module

---

src/dolphin/stitching.py

Adding `-tap` was creating occasional duplicated rows based on something in the `gdal_merge.py` blocking scheme.
The result of `np.diff(merged, axis=0) == 1` looked like this for 2 bursts:
(Note that this is not related to any burst-jump artifacts. the line is constant in `y`)
Removing the `-tap` gets rid of this

Remove `-tap` option from `gdal_merge.py` call

---

src/dolphin/stitching.py
src/dolphin/unwrap/_constants.py
src/dolphin/unwrap/_isce3.py
src/dolphin/unwrap/_snaphu_py.py
src/dolphin/unwrap/_tophu.py
src/dolphin/unwrap/_unwrap.py
src/dolphin/workflows/_cli_config.py
src/dolphin/workflows/config/_common.py
src/dolphin/workflows/unwrapping.py

When [passing a mask](https://github.com/sssangha/dolphin/blob/0a67fa1ee77e70f0171aa96a8ea1d949453f775a/src/dolphin/unwrap/_unwrap.py#L37) for unwrapping, it seems to be ignored even though an INT mask was clearly generated (see screenshot below):
After digging a bit, I realized that this was because by default the [zero_where_masked](https://github.com/sssangha/dolphin/blob/0a67fa1ee77e70f0171aa96a8ea1d949453f775a/src/dolphin/unwrap/_unwrap.py#L38) parameter is set to False, which according to this conditional [downstream](https://github.com/sssangha/dolphin/blob/0a67fa1ee77e70f0171aa96a8ea1d949453f775a/src/dolphin/unwrap/_snaphu_py.py#L90) must be set to true in addition to providing a mask.
In this PR, I've exposed this `zero_where_masked` parameter so it can be toggled. It seems to …

Toggle zero mask and apply to unw phase field

---

src/dolphin/atmosphere/ionosphere.py
src/dolphin/atmosphere/troposphere.py
src/dolphin/stack.py

The get_dates function returns all the dates in the file name but the code was expecting only 3. Since the naming convention in the production data has 4, the output of this function had to be modified.

fix bug for get dates

---

src/dolphin/atmosphere/ionosphere.py
src/dolphin/atmosphere/troposphere.py

required metadata is not currently included in compressed SLCs, we need to add it in a separate PR
this is a temporary fix

temporary fix for compressed SLC metadata

---

src/dolphin/unwrap/_constants.py
src/dolphin/unwrap/_utils.py

Currently, masked conncomp files would have a filename with the `*.unw.conncomp.zeroed.cor.tif` suffix.
I've proposed changes which would enforce a filename suffix of `*.unw.conncomp.zeroed.tif` instead.

Enforce convention for conncomp files to be consistent with unw files

---

.github/workflows/test-build-push.yml
src/dolphin/timeseries.py
tests/test_timeseries.py

Use a batch `jnp.polyfit` for unweighted velocity fitting

---

CONTRIBUTING.md
src/dolphin/interferogram.py
src/dolphin/io/__init__.py
src/dolphin/io/_core.py
src/dolphin/io/_utils.py
src/dolphin/stitching.py
src/dolphin/workflows/displacement.py
src/dolphin/workflows/stitching_bursts.py

- Fixed the options missing from the `stitching` call, which was leading to uncompressed stitched outputs
- Made a helper function to setup different GDAL compression settings
- Made `repack_rasters` to call `gdal.Translate` on multiple images to recreate with new compression settings.
- For instance, we'll want to call with `lerc_deflate` to compress correlation files to a max precision of something like 0.001 - 0.005

Add functions for compression options and repacking

---

src/dolphin/timeseries.py

The symlink fails when run inside docker, even if it works outside. Gives an error like 
```
File "/opt/conda/lib/python3.12/site-packages/osgeo/gdal.py", line 8817, in Open
return _gdal.Open(*args)
^^^^^^^^^^^^^^^^^
RuntimeError: /work/scratch/timeseries/scratch/unwrapped/20221107_20221119.unw.tif: No such file or directory
```

Copy over rasters to `timeseries/`, dont symlink

---

src/dolphin/interferogram.py
src/dolphin/stitching.py
src/dolphin/workflows/stitching_bursts.py

Right now, for a medium workflow (100 interferograms, 15 burst IDs), the stitching step takes ~30 minutes. It's needlessly serial.
- Add option to run `merge_dates` with `thread_map`
- Same for `estimate_interferometric_correlations`
- Default for the main workflow is 3 workers, to give some parallelism but not overwhelm system IO

Let `stitching_bursts.py` run in parallel

---

src/dolphin/unwrap/_unwrap.py

The output path to unwrapped file was set to the interpolated/filtered file instead of the one with ambiguities added
This is used in orca

correct the unwrapped file output path

---

src/dolphin/unwrap/_unwrap_3d.py
src/dolphin/workflows/config/_unwrap_options.py

The fuller variable names were not work the annoyance of having it be different/explaining the `alias` option of Pydantic.

Minor changes in `spurt` config to match its naming onventions

---

requirements.txt
src/dolphin/_show_versions.py
src/dolphin/interferogram.py
src/dolphin/io/_utils.py
src/dolphin/workflows/stitching_bursts.py
tests/test_show_versions.py

Now the `show_versions` doesn't have to duplicate the list of dependencies (which was out of date).
Also fixes Ryan's problem,
```
RuntimeError: Cannot create TIFF file due to missing codec for lerc_deflate.
```

Let `show_versions` read `importlib.metadata`, use `keep_bits`, not `lerc`

---

.github/workflows/test-build-push.yml
src/dolphin/_show_versions.py
src/dolphin/unwrap/__init__.py
src/dolphin/unwrap/_isce3.py
src/dolphin/unwrap/_snaphu_py.py
src/dolphin/unwrap/_unwrap.py
src/dolphin/unwrap/_whirlwind.py
src/dolphin/workflows/config/_enums.py
tests/test_unwrap.py

Adds whirlwind as an alternative phase unwrapping option.
The whirlwind repo is still private currently, but should be accessible to isce-framework members and to the CI. Adding it to dolphin will allow for valuable initial testing and comparison to other unwrappers. The remaining functionality in dolphin should be unaffected for folks who don't have whirlwind installed.
Another limitation is that whirlwind currently does not provide a connected components layer. For now, the whirlwind wrapper also depends on snaphu-py to compute connected components (as well as for raster I/O).

Add whirlwind unwrapper

---

.github/workflows/test-build-push.yml

The whirlwind repo is still private within isce-framework and therefore requires a token to access via GitHub Actions. According to https://github.com/orgs/community/discussions/46566, the one-time-use `GITHUB_TOKEN` that's supplied to each GHA job doesn't have permissions to access private repos within the same organization. Instead, we would need to setup a PAT or some other less-secure solution.
With this in mind, I think my preferred approach is to simply disable whirlwind test(s) in CI until the repo becomes publicly accessible.

Remove whirlwind from the CI environment

---

src/dolphin/interferogram.py
tests/test_interferogram.py

They can be generally useful for computing indexes without forming actual VRT files

Make network formation `staticmethod`s public

---

src/dolphin/io/_core.py

size difference from better interleave for 2-band compressed:
```
ls -lh
305M Jul 23 14:28 compressed_interleave_by_band.tif
551M Jul 23 13:54 compressed_20170606_20171227_20180625.tif
```

Interleave GTiffs by band

---

src/dolphin/unwrap/_unwrap.py

Dolphin may do some interferogram pre-processing, such as interpolation and/or Goldstein filtering, prior to unwrapping. In order to preserve congruence with the original wrapped phase values, the ambiguity numbers for the initial unwrapped result are then transferred onto the original wrapped phase in order to form the final unwrapped phase.
The current strategy for estimating the ambiguity numbers is to compute the difference between the unwrapped phase and the pre-processed (i.e. interpolated, filtered) wrapped phase values. However, we found that this sometimes introduces phase discontinuities near fringe boundaries.
The new strategy introduced in this PR is to compute the difference between the unwrapped phase and the \*original\* wrapped phase data and then round that to the nearest …

Improve code for transferring unwrapped phase ambiguities

---

README.md
docs/gpu-setup.md
src/dolphin/masking.py
src/dolphin/workflows/config/_displacement.py
src/dolphin/workflows/single.py
tests/test_masking.py

- creates `load_mask_as_numpy` in `masking`
- Fixes `combine_mask_files` to use `io.write_arr` rather than `gdal` bindings. changes convention default to be all `ZERO_IS_NODATA`

Move mask loading function into `masking.py`

---

src/dolphin/_log.py
src/dolphin/interferogram.py
src/dolphin/stitching.py
src/dolphin/workflows/stitching_bursts.py

Speeds up reruns for end-of-displacement testing

Skip correlation estimate for files that exist 

---

src/dolphin/filtering.py
tests/test_filtering.py

We can get a temporarily working version that doesn't quite do the edges the same, but works to fix #371 . This just uses `np.pad` with `mode="reflect"`. It doesn't 
https://scikit-image.org/docs/stable/auto_examples/transform/plot_edge_modes.html#interpolation-edge-modes has an illustration of what the pad modes look like. I think we were going for either "reflect" or "symmetric".
Also, we were using a `sigma` of ~200 pixels, which is kinda slow for our huge 7000x9000 pixel images. Using [fourier_gaussian](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.fourier_gaussian.html#scipy.ndimage.fourier_gaussian) should be a bit quicker, looks like is ~2 minutes in this PR vs ~5 minutes in main
```
In [42]: %time filt_main = …
```

Simplify `filter_long_wavelength` to use `np.pad(..., mode="reflect")`

---

src/dolphin/io/_process.py
src/dolphin/timeseries.py
tests/test_timeseries.py

- The numpy array is now smaller
- The empty `20200101_20200101` raster is skipped

Skip zero raster output by timeseries inversions

---

src/dolphin/timeseries.py

Using the wrong array to count labels led to `(0, 0)` as the reference

Fix reference point selection labels

---

src/dolphin/stitching.py
src/dolphin/workflows/displacement.py

These need to not be required imports for running displacement

Remove `atmosphere` imports from the main path

---

src/dolphin/phase_link/covariance.py

Originally it was structured to have better data locality to speed up the covariance estimation. After more testing, the difference in runtime is not noticeable enough to be worth the complexity increase.

Remove transposed versions of functions in `covariance`

---

src/dolphin/phase_link/_core.py

Despite making the visualization close to the original SLCs, this was likely the culprit of https://github.com/OSGeo/gdal/issues/10559

Set `use_slc_amp` default to False

---

src/dolphin/workflows/displacement.py

As pointed out by @collinss-jpl , this used to not check for `None`. Since the default initializer is an empty list, this fails after loading the yaml and creating `[]`.

Fix `displacement.run` to avoid troposphere computation with empty list

---

src/dolphin/workflows/wrapped_phase.py

Unnecessary to redo for reruns that already computed it.

Skip `combine_mask_files` if the output already exists

---

src/dolphin/filtering.py
src/dolphin/phase_link/_core.py
src/dolphin/workflows/config/_common.py

Background on why this was the default before: For the simple "rect" SHP finder (which is no SHP finding- just averaging in a rectangular window like basic multilooking), the results can sometimes look much better if you mask out very bright pixels (which dominate the sum in a window).
Since the normal default uses the GLRT SHP algorithm, that algorithm should take care of this problem on its own; users picking the `rect` method can choose to turn this back on as well.

Add config option to avoid PS pixels during phase linking

---

src/dolphin/unwrap/_snaphu_py.py
src/dolphin/unwrap/_unwrap.py

Updates the unwrapping code to make sure we pass the same mask to the connected component regrowing step (when applicable) that we passed to the original unwrapper. Previously in the connected component regrowing step, we only masked out pixels with coherence equal to zero.

Use the same mask for unwrapping and conncomp regrowing steps

---

src/dolphin/unwrap/_unwrap.py

Add `ignore_errors=True` to `rmtree` for scratch removal

---

.dockerignore
src/dolphin/_overviews.py
src/dolphin/io/_readers.py
src/dolphin/unwrap/_unwrap_3d.py
src/dolphin/workflows/displacement.py

As a stopgap so we don't have a completely different set of output files from one unwrapping method, create connected component labels ~as just a 0/1 mask based on what we pass to `spurt`~:
- Recreate the binary mask that `spurt` uses
- Dilate if by `dilate_by` pixels, by default 25 (or about 750 meters of expansion for 30 m pixels)
- Run `ndimage.label` on the dilated
- Reset the pixels which were 0 to have 0 label
I'm avoiding the snaphu connected component grower because 
1. the different cost function of snaphu may not align with what `spurt` considers good, 
2. the unwrapping errors on an irregular grid seem to manifest differently than what snaphu's errors look like,
3. I believe that if we actually had sparse pixels (which may be good, just disconnected from immediate neighbors), …

Create `.conncomp` files for `spurt` from temporal coherence

---

src/dolphin/filtering.py
src/dolphin/interferogram.py
src/dolphin/unwrap/_post_process.py

- Reduce artifacts by ignoring `nan`/0 single pixel values in the correlation estimation
- Use a Gaussian window instead of uniform boxcar

Setup `gaussian_filter_nan` in utils, use in `estimate_correlation_from_phase`

---

src/dolphin/unwrap/_unwrap_3d.py

The connected component labels are missing geo-metadata.

Add `like_filename` for `spurt` connected components

---

src/dolphin/workflows/_utils.py
src/dolphin/workflows/displacement.py
tests/test_workflows_utils.py

Bug found by @collinss-jpl : What was happning was
- the `group_by_date` function will run through all files given and, if no date is matched, puts these files with the `()` key
- this key is overwritten in the second ionosphere format iteration.
This adds a test for the failing case (with just a subset of the old filenames), and moves the parsing to a separate function to test.

Fix ionosphereic date parsing and grouping

---

src/dolphin/timeseries.py
tests/test_workflows_displacement.py

After re-referencing, the nodata values at the boundaries are turned into random numbers. This now uses masked arrays which can retain the mask during shifting/scaling.
In a small test, the unwrapped interferograms have ~93% valid data:
```
$ gdalinfo -stats unwrapped/20180210_20180222.unw.tif | tail -1
STATISTICS_VALID_PERCENT=93
```
but the timeseries rasters have ~all "valid data":
```
$ gdalinfo -stats timeseries/20180210_20180222.tif | tail -1
STATISTICS_VALID_PERCENT=99.999
```
after this PR, this is fixed:
```
$ gdalinfo -stats timeseries/20180210_20180222.tif | tail -1
STATISTICS_VALID_PERCENT=93
```

Fix handling of `nodata` during timeseries conversion to meters

---

src/dolphin/workflows/wrapped_phase.py

For a starting stack without compressed SLCs, any `extra_reference_date` was getting ignored.

Dont short-circuit `extra_reference_date` change over

---

docs/requirements.txt
src/dolphin/timeseries.py
src/dolphin/workflows/wrapped_phase.py
tests/requirements.txt
tests/test_workflows_displacement.py

Currently we would run the inversion for unwrapped outputs like `1_2, 1_3, 3_4, 3_5` to make `1_2, 1_3, 1_4, 1_5`.  Since this is not an output that normal use cases would run into, this reverts the check to simply look at the number of interferograms. 
Now those unwrapped outputs would just be moved into the `timeseries/` folder, but get shifted by the reference point, and converted to meters.

Change `is_single_reference` to only look for number of interferograms

---

.github/workflows/test-build-push.yml
docs/references.bib
pyproject.toml
src/dolphin/atmosphere/weather_model.py
src/dolphin/goldstein.py
tests/make_netcdf.py
tests/test_unwrap.py

Closes #251 
For a current input with rotated phase (e.g. a geocoded interferogram):
The edge blocks leave slightly non-zero values (here is using `np.ma.masked_equal(phase, 0)`):
The result of this PR:

Apply nan/0 mask to output of `goldstein` filter

---

src/dolphin/unwrap/_post_process.py
src/dolphin/unwrap/_unwrap_3d.py
src/dolphin/workflows/displacement.py
src/dolphin/workflows/stitching_bursts.py

Allows adjusting it after the fact by `disp-s1`. Removed the unpacking of 7 files in favor of using the attribute names to refer to the paths.

Use `dataclasses` instead of `NamedTuple` for displacement, stitched outputs

---

src/dolphin/unwrap/_unwrap_3d.py
src/dolphin/utils.py

This lets us skip/warn if needed for `get_nearest_idx`.

Add `outside_input_range` options to `get_nearest_date_idx`

---

src/dolphin/timeseries.py
tests/test_workflows_displacement.py

By not including `units = ...`, everything after the reference change lost the `meters` from unwrapping
```
$ rio info scratch/timeseries/20180722_20190711.tif | jq .units
[
"meters"
]
$ rio info scratch/timeseries/20190711_20190717.tif | jq .units
[
null
]
```

Pass through `units` during `timeseries._redo_reference`

---

src/dolphin/workflows/single.py
src/dolphin/workflows/wrapped_phase.py

Discovered this after repeated batch runs of `disp-s1`, manually passing in stacks with compressed SLCs:
```python-traceback
File "/u/aurora-r0/staniewi/repos/dolphin/src/dolphin/workflows/wrapped_phase.py", line 171, in run
) = sequential.run_wrapped_phase_sequential(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/u/aurora-r0/staniewi/repos/dolphin/src/dolphin/workflows/sequential.py", line 114, in run_wrapped_phase_sequential
run_wrapped_phase_single(
File "/u/aurora-r0/staniewi/repos/dolphin/src/dolphin/_decorators.py", line 106, in wrapper
result = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/u/aurora-r0/staniewi/repos/dolphin/src/dolphin/workflows/single.py", line 239, in run_wrapped_phase_single
cur_comp_slc = compress(
^^^^^^^^^
File …
```

Fix the relative index used to make compressed SLCs

---

src/dolphin/io/_blocks.py
tests/test_io_blocks.py

Having a `HalfWindow(1, 1)` and `Strides(3, 3)` should lead to non overlapping blocks. The output trimming slices were working, but input (full res) slices were `slice(0, 0)` instead of `slice(0, None)`

Fix `in_trim_slice` size for non overlapping blocks

---

src/dolphin/unwrap/_unwrap.py
src/dolphin/unwrap/_unwrap_3d.py

Memory usage seems to be much higher when using `spawn` instead of `fork`, possibly due to passing in the Delaunay object.
Havent gotten to really debug that problem yet. [fil](https://pythonspeed.com/fil) seems like a good option to try later.

Call spurt from `subprocess` to avoid fork issues

---

src/dolphin/unwrap/_snaphu_py.py

For a frame sized 8k x 9k, 0.01 is >700,000 pixels
Its very reasonable to have smaller legitamate connected components than this

Add `min_conncomp_frac`, lower default to 0.001

---

src/dolphin/workflows/config/_unwrap_options.py

The target of 1e6 points seems okay per tile, but frames with >30 million points were getting 2 million points and causing hangups.

Increase `spurt`` max_tiles` default to 49 to have smaller MCF problems

---

src/dolphin/stack.py

Sara found the problem with repeatedly running disp-s1 with a reference update:
```
ministack 0:
compressed_t042_088905_iw1_20160810_20160810_20170407.h5 
ministack1:
compressed_t042_088905_iw1_20170817_20170419_20171028.h5 
ministack2:
compressed_t042_088905_iw1_20160810_20171109_20180508.tif
```
Even though in Run2 we are making interferograms relative to 20170817, the `compressed_reference_idx` snapped back to 0.

Use `output_reference_idx` as the default for creating compressed slcs with `ALWAYS_FIRST`

---

src/dolphin/workflows/single.py

OOM errors at the end of wrapped phase estimation were likely cause by this.

Pass through `block_shape` to `create_similarities` after phase linking

---

src/dolphin/workflows/wrapped_phase.py

Due to the geolocation errors, sometimes 200 pixels is not quite enough. 800 pixels on each edge seems conservative
Subsampled by (3, 6) for the rows, cols:
The block was skipped because the 200 pixel buffer on ESA's bounding box wasn't sufficient

Increase the `buffer_pixels` when making OPERA CSLC mask

---

src/dolphin/io/_core.py

- Allows us to use an S3 url as the `like_filename` argument
- All the `io.get_raster_` function now work with s3 urls

Setup conversion to `/vsis3` when reading from S3 using `osgeo.gdal`

---

src/dolphin/timeseries.py
tests/test_timeseries.py

Currently running snaphu with nearest-N interferograms can leave some pixels as basically "nodata" from being labelled 0 in the connected components.
Now these pixels will be ignored during `invert_stack`.
Rough timing estimates for a stack of 15 dates, forming nearest 3 interferograms, solving for a block of (128, 128) pixels:
```python
In [164]: A = np.random.randn(39, 14)
In [165]: x_true = np.arange(14)
In [166]: b = A @ x_true
In [167]: B = np.tile(b[:, None], (1, 128*128))
In [168]: M = np.random.rand(*B.shape) > 0.1 # Pretend 10% are censored
In [171]: %timeit x, res = timeseries.censored_lstsq(A, B, M)
205 ms ± 25.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Add `censored_lstsq` to solve least squares with missing data

---

src/dolphin/interpolation.py
src/dolphin/unwrap/_tophu.py
src/dolphin/unwrap/_unwrap.py
tests/test_interpolation.py
tests/test_unwrap.py

Currently the outside, nodata values will all fall below the threshold, leading to the most possible pixels summed for the area we dont care about.
The speedup is minor for normal, full frame interferograms, but for the degenerate case of a large interferogram with mostly nodata (e.g. a fixed frame with only 1 or 2 bursts running for a quick CI test), the interpolation takes very long:
```python
In [5]: %time interpolate(ifg, weights, weight_cutoff=0.3).shape
CPU times: user 24min 54s, sys: 6.71 s, total: 25min 1s
Wall time: 4min 15s
Out[5]: (7091, 9736)
```
with this change
```python
In [4]: %time interpolate(ifg, weights, weight_cutoff=0.3).shape
CPU times: user 1.41 s, sys: 671 ms, total: 2.08 s
Wall time: 2.45 s
Out[4]: (7091, 9736)
```

Skip nodata values of interferograms when interpolating

---

src/dolphin/unwrap/_unwrap_3d.py

`spurt` running on AWS was hitting weird `BrokenProcessPool` errors. Difficult to debug due to AWS opaqueness. Rerunning may help, since spurt has the JSON and hdf5 tile checkpoint files.

Add a retry to spurt for brokenprocesspools

---

src/dolphin/filtering.py

@forrestfwilliams noted that the out-of-bounds pixels are nan, but the masked pixels are 0.
This should fix that problem by using `total_valid_mask` instead of `in_bounds_mask` at the end of the function

Add `fill_value` to `filter_long_wavelength`, apply to masked pixels if provided

---

src/dolphin/timeseries.py
src/dolphin/unwrap/_post_process.py
src/dolphin/unwrap/_unwrap_3d.py

This should print the logging to the terminal to see the progress.
Symlink check is to avoid `FileExistsError` after a restart for the line `new_path.symlink_to(fn)`

Avoid capturing all logging from spurt

---

src/dolphin/utils.py

Using `lanczos` resampling here may be been accidental, or may have been changed in `merge_images` after it was created. 
Currently on disp-s1 frame 8882, we see this for the `los_east` 30 meter dataset
with nearest
(colorbar is different from a lack of spurrious 0.01 values)

Use `nearest` sampling to stitch static layers

---

src/dolphin/workflows/wrapped_phase.py

The current logic correctly relabelled the interferograms across the reference-date change; however it used the same reference phase (by using `convert_pl_to_ifg`) and didn't apply the new reference phase. 
The other change is to fix the unclear logic about when to apply the reference date, if it's supplied: the only times we ignore during `wrapped_phase` are if we're using spurt (i.e. `is_using_spurt`) or if we've requested nearest-3/nearest-n interferograms (`is_using_short_baseline_ifgs`). The logic looks different because the old one was subtly wrong, but just didn't come up in practice.

Fix `extra_reference_date` logic for single reference unwrapping

---

conda-env.yml
src/dolphin/unwrap/_post_process.py
src/dolphin/unwrap/_unwrap_3d.py
src/dolphin/workflows/config/_unwrap_options.py
src/dolphin/workflows/wrapped_phase.py

Main branch currently takes ~50 seconds for an interferogram; this PR is taking around 13 seconds.
Also adding the flag to turn this off entirely; future work could be to give some other guess within spurt instead of this workaround.

Speed up the post-`spurt` 2-pi ambiguity interpolation

---

src/dolphin/io/_core.py

Use `fspath` when opening with `gdal` to support older versions

---

src/dolphin/workflows/stitching_bursts.py

Closes #144
The `lanczos` filter was leading to pixels above 1 in the merged temporal coherence image, despite the max being 1.0 per burst.
This is also likely the reason for negative coherences, though we can reopen if any new instances are spotted (hasn't been seen in a year)
Before the fix:
```
$ rio info --stats scratch/historical/t034_071057_iw2/linked_phase/temporal_coherence_average_20160927_20170326.tif
0.10250737518072128 1.0 0.5941266093428491 0.16596814123869957
$ rio info --stats scratch/historical/interferograms/temporal_coherence.tif
0.01056671142578125 1.15234375 0.5833594791456398 0.19027603197546147
```
and these were only happening on bursts which required reprojection:
```
$ rio info --crs scratch/historical/interferograms/temporal_coherence.tif
EPSG:32615
$ rio info …
```

'Use `nearest` resampling for merging temporal coherence

---

src/dolphin/io/_readers.py
tests/test_io_readers.py

Slices like `slice(n, n+1)` currently get squeezed out of the `RasterReader` and `RasterStackReader` classes.
~TBD: if we should make the default `keepdims=True`, or make the default the same as current behavior with `keepdims=False`.~
I have made the default `keepdims=True`, since, in dolphin, we are really using these dataset readers in the context of block-based processing. There are more headaches involved with a dimension accidentally dropping out than having an extra singleton dimension. Since we're adding this as an init option, there's still the ability to squeeze out dimensions if desired for other purposes.

Add `keepdims` options to reader classes to avoid squeezing singleton dims

---

src/dolphin/stack.py

The current imagined use case for `LAST_PER_MINISTACK` compressed SLC's is to always make the shortest possible baseline interferograms. This means a sensible default is to set the output reference to be the most recently created compressed SLC (i.e. `output_reference_idx = num_ccslc - 1`).
As expected, the tests on Kilauea show better results than if we include longer interferograms.

Use the most recent compressed SLC as output for `LAST_PER_MINISTACK`

---

src/dolphin/filtering.py
src/dolphin/phase_link/simulate.py
tests/test_filtering.py

Testing on a horizontal ramp:
the main branch leaves an edge effect:
This PR gives all zeros, as we would want.
Sanity check on small, real unwrapping interferogram looks okay as well.

Adapt short wavelength filter to use `gdal_fillnodata` to mitigate edge effects

---

src/dolphin/stack.py

If we pass a `LAST_PER_MINISTACK`, we want that output index, regardless of whether we pass a `compressed_idx` or not.

Set `output_reference_idx` separately from `compressed_reference_idx`

---

src/dolphin/__init__.py
src/dolphin/timeseries.py
src/dolphin/unwrap/_unwrap.py

The interpolate one gets numba, unwrap, leads to much longer import times for CLIs
Also fix the `get_dates` within time series for cases with longer filenames.

Remove import for `goldstein` and `filtering` from top level `__init_.py`

---

docs/javascripts/mathjax.js
mkdocs.yml
src/dolphin/_types.py
src/dolphin/interferogram.py
src/dolphin/stack.py
src/dolphin/timeseries.py
tests/test_interferogram.py

Unclear exactly why this fails in mkdocstrings: https://readthedocs.org/projects/dolphin-insar/builds/27059026/
Also changes the mathjax snippets based on more recent suggestions here: https://squidfunk.github.io/mkdocs-material/reference/math/#mathjax

docs: Fix mathjax render, fix broken `DateOrDatetime` error

---

CHANGELOG.md
src/dolphin/_cli_timeseries.py
src/dolphin/timeseries.py
src/dolphin/workflows/config/_enums.py
src/dolphin/workflows/displacement.py
tests/test_timeseries.py

The default choice right now uses `argmax`, which, by numpy ordering, will be the edge of the possible pixels:
A safe one is more toward the center of the biggest connected component intersection. 
Scipy has the `center_of_mass` function, with the caveat being that the exact centroid may not one of the candidate pixels.

Refactor `select_reference_point` to pick the centroid of high-coherence candidate pixels

---

src/dolphin/io/_core.py
src/dolphin/utils.py
src/dolphin/workflows/single.py
tests/test_utils.py

- Adds `utils.grow_nodata_region`
- Runs function during phase linking workflow to remove bad border pixels from SHP rasters.
Fixes #547

Add `utils.grow_nodata_region` to remove bad borders from `shp_counts.tif`

---

src/dolphin/io/_core.py

As a precaution against striping found here: https://github.com/nasa/PROTEUS/pull/54

Move `WriteArray` calls after `SetNoDataValue` calls

---

scripts/write-gamma-vrts.py

Addressing questions about setup for GAMMA inputs: https://github.com/isce-framework/dolphin/discussions/260#discussioncomment-12872008
TODO: 
- Add a "How To" short section fo docs for "How to run on Gamma coregistered SLCs"
- Decide if this should scripts, or somewhere else... if someone `pip install dolphin`, right now they dont get the `scripts/` dir

Add script to read GAMMA `.rslc` binary SLCs

---

src/dolphin/timeseries.py

In cases where the time series files have already been referenced, there is no need to have a `reference_point` that gets subtracted before fitting. Hence, the argument should be optional here.

Make `reference` optional for velocity fitting

---

src/dolphin/stack.py
src/dolphin/workflows/config/_common.py
src/dolphin/workflows/sequential.py
src/dolphin/workflows/wrapped_phase.py
tests/test_stack.py

We want the `output_reference_idx` to move forward one each time when doing `ALWAYS_FIRST`. Otherwise, the results look much noisier (though still roughly correct)
Note that this was previously found by @mirzaees , but I lost how important it was in the refactors of `stack.py` of #334 since the outputs can still look somewhat correct.
Before (main): 
After 
I'm not fully deleting the `output_reference_idx` at the moment in case we do want to pass in some specific date that we know should be the "best" single-reference interferogram date to use

Simplify reference index logic for `ALWAYS_FIRST` in `stack.py`, cut `FIRST_PER_MINISTACK`

---

src/dolphin/io/_utils.py
src/dolphin/stitching.py
src/dolphin/unwrap/_post_process.py
src/dolphin/unwrap/_tophu.py
src/dolphin/unwrap/_utils.py
src/dolphin/utils.py
src/dolphin/workflows/corrections.py
tests/test_unwrap.py

- Remove `_format_for_gdal()` which is never invoked.
- Remove the numba-decorated phase difference helpers `compute_phase_diffs`
- Move the _redirect_unwrapping_log() to dolphin/unwrap/_tophu.py).
- Update type annotations in unwrap._utils
- Move `prepare_geometry` to `corrections` workflow

Remove unused `_utils` helper functions

---

src/dolphin/workflows/config/_common.py
src/dolphin/workflows/wrapped_phase.py
tests/test_workflows_config.py

Problem with `bounds_epsg` was noted in https://github.com/isce-framework/dolphin/discussions/590#discussioncomment-13144615 by @giorgoskouroupis

`OutputOptions`: Only require `bounds_epsg` if specifying `bounds`, cut `resolution`

---

src/dolphin/workflows/displacement.py
tests/test_io_writers.py
tests/test_workflows_displacement.py

Currently the multi-burst outputs have one directory per burst ID, while the single-burst is a special case that moves those contents to the top level `work_directory`.
This is unnecessary, and has led to problems such as https://github.com/opera-adt/disp-s1/issues/296
This always places the phase linking results in one directory up from `work`, naming it `phase_linking` in case it's a general non-OPERA swath.

Remove single-burst special case, keep phase linking results to `phas… e487ce2  …e_linking/`

---

src/dolphin/atmosphere/ionosphere.py
src/dolphin/timeseries.py
src/dolphin/unwrap/_unwrap_3d.py
src/dolphin/workflows/wrapped_phase.py

No functional changes - simplify ensuring that the specified date format we want gets used in later timeseries stages, rather than jumping to assume it's `%Y%m%d` there.

Add `fmt=file_date_fmt` to all `get_dates` call to avoid file format assumptions

---

src/dolphin/workflows/config/_common.py
src/dolphin/workflows/displacement.py
src/dolphin/workflows/sequential.py
src/dolphin/workflows/single.py
src/dolphin/workflows/wrapped_phase.py

Improves performance for single burst (large swath, like NISAR) by adding block-level parallelism.
- Uses `ThreadPoolExecutor` since core JAX functions release GIL
- Refactored each block's processing to an inline `_process_block` function
- One tricky bit is the need for `read_lock` and `write_lock` to prevent race conditions on the background readers/writers
Closes #265 
Test case for a synthetic stack, shape `(15, 1997, 2138)`
Main branch: time for phase linking iteration: 51 seconds
```
dolphin run dolphin_config.yaml  114.60s user 8.00s system 203% cpu 1:00.17 total
```
PR Timings
- 1 worker: 55 seconds
```
dolphin run dolphin_config.yaml  112.15s user 7.90s system 192% cpu 1:02.33 total
```
- 3 workers: 24 seconds 
```
dolphin run dolphin_config.yaml  129.69s user 8.51s system 443% …
```

Parallelize phase linking for single-swath case in `single.py`

---

src/dolphin/workflows/displacement.py
tests/test_workflows_displacement.py

The `timeseries` and `unwrapped` directories within phase linking folders were being created, but not removed. the `_remove_dir_if_empty` was added to do this, but was not used correctly.

Fix: Remove per-burst phase linking dirs that are empty

---

src/dolphin/timeseries.py
src/dolphin/workflows/displacement.py
tests/test_workflows_displacement.py

Pass through `timeseries_options.reference_point` during `displacement.py` workflow

---

src/dolphin/cli.py
tests/test_cli.py

Instead of `IndexError: list index out of range` due to the `sys.argv[1]`, this raises the default `tyro` error.

Throw better error for `dolphin` empty cli

---

src/dolphin/stitching.py
tests/test_stitching.py

`dest_epsg` in `merge_by_date` and `merge_images` functions allows specifying the output projection, with a default behavior of finding the most common projection among input files.
Closes #248

`stitching.py`: Add support for specifying output projection
